name: ci/cd

on:
  push:
    branches: ['master']



jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh
        uses: appleboy/ssh-action@master
        with:
          host: "51.250.28.105"
          username: "epanchenko"
          key: ${{ secrets.SSH_KEY }}
          script: | 
            whoami
            curl -H Metadata-Flavor:Google 169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token | \
            cut -f1 -d',' | \
            cut -f2 -d':' | \
            tr -d '"' | \
            sudo docker login --username iam --password-stdin cr.yandex
            sudo docker pull cr.yandex/crpa0nrlk4sddkdrjoqd/my-first-registry:feb3971d10d73b1796d426fcbd55e14c890d70dc
            sudo docker stop container-counter
            sudo docker run -d -p 3000:3000 --name container-counter --rm e5180bf02b69
