name: Test eslint

on:
  push:
    branches: ['master']

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh
        uses: appleboy/ssh-action@master
        with:
          host: "51.250.28.105"
          username: "epanchenko"
          key: ${{ secrets.SSH_KEY }}
          script: | 
            whoami
            sudo docker pull cr.yandex/crpk28lsfu91rns28316/yc-coi-github-action:d301d44a3d87070e6fbc8891f7aa79c76943b451
