name: Test eslint

on:
  push:
    branches: ['master']

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh
        uses: appleboy/ssh-action@master
        with:
          host: "51.250.28.105"
          username: "epanchenko"
          key: ${{ secrets.SSH_KEY }}
          script: | 
            whoami
            dir
